import { ProductData } from '../types/product';

export const INITIAL_PRODUCTS: ProductData[] = [
  {
    id: 'sample-1',
    seq: 1,
    produit: 'Chasse-moustique à photocatalyseur',
    marche: 'China',
    sourcing: 1760,
    poids: 0.33,
    modeimport: 'bateau',
    tarifbateau: 3500,
    tarifavion: 9000,
    concurrent: '',
    cac: '',
    livraison: '',
    vente: '',
    douleur: '',
    nonres: '',
    etendue: '',
    impact: '',
    waouh: '',
    innovant: '',
    nonsaison: '',
    habitudes: '',
    poidsfacteur: '',
    cible: '',
    angle: '',
  },
  {
    id: 'sample-2',
    seq: 2,
    produit: 'Lampe Anti-Moustique Photocatalytique',
    creative: 'https://tiktok.com/@votre_compte/video_demo',
    alibaba: 'https://www.alibaba.com/product-detail/1601709112646.html',
    siteweb: 'https://votre-boutique.com/lampe-anti-moustique',
    marche: 'Chine',
    concurrent: 15000,
    sourcing: 1800,
    poids: 0.35,
    modeimport: 'avion',
    tarifavion: 9000,
    tarifbateau: 3500,
    cac: '',
    livraison: '',
    vente: 10500,
    douleur: 5,
    nonres: 4,
    etendue: 5,
    impact: 4,
    waouh: 4,
    innovant: 4,
    nonsaison: 4,
    habitudes: 5,
    poidsfacteur: 5,
    cible: 'Parents / Jeunes cadres à Cotonou',
    angle: 'Anti-Dantokpa : Zéro chimie, moteur renforcé & garantie 7j',
  },
];
